myweb/myweb/urls.py
import statistics
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myweb/tienda/urls.py
from logging import root
from xml.dom.minidom import Document
from django.conf import settings
from django.urls import path
from .models import Avatar

from myweb.settings import STATIC_URL
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('acerca de mi/', views.acerca_de_mi, name='acerca_de_mi'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('agregar_avatar', views.agregar_avatar, name='agregar_avatar'),
    path('Auth/mensaje/', views.mensaje, name='mensaje'),
    
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
    
]

myweb/tienda/models.py
from email.mime import image
from io import UnsupportedOperation
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Avatar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='media/avatar', null=True, blank=True)
    
    class meta:
        verbose_name = "avatar"
        verbose_name_plural = "avatares"


class Categorias(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
    class Meta:
        db_table = "categorias"
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


#modelo Productos
class Productos(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imgproductos/%Y/%m/%d', blank=True)
    descripcion = models.CharField(max_length=500)
    precio = models.IntegerField()
    stock = models.IntegerField(null=True, default=0)
    categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    oferta = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre
    class Meta:
        db_table = 'contacto'
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'
        ordering = ['nombre']
        
class Mensaje(models.Model):
    user = models.TextField()
    mensaje = models.TextField()
    fecha = models.DateTimeField()
    
    def __str__(self):
        return self.user
    class Meta:
        db_table = 'mensaje'
        verbose_name = 'Mensaje'
        verbose_name_plural = 'Mensajes'
        ordering = ['fecha']


# Model Carrito

myweb/tienda/forms.py
from django import forms
from .models import Contacto, Mensaje, Productos, Categorias, Avatar
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MensajeForm(forms.ModelForm):
    
    class Meta:
        model = Mensaje
        widgets={
            'mensaje': forms.Textarea(attrs={
                'rows':5,
                'cols':30
                }),
        }
        fields = '__all__'

class ConctactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        widgets={
            'mensaje': forms.Textarea(attrs={
                'rows':5,
                'cols':30
                }),
        }
        fields = '__all__'


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Productos
        fields = ["nombre", "descripcion", "precio", "stock", "categoria", "oferta", "imagen"]
        

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categorias
        fields = ["nombre"]

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)
    first_name = forms.CharField(label="Nombre", required=False)
    last_name = forms.CharField(label="Apellido", required=False)
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput) # la contraseña no se vea
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput)
   
  

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

        #help_texts = {k:"" for k in fields}

class UserEditForm(UserCreationForm):

    username = forms.CharField(label="username")
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput, required=False)
    
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class AvatarForm(forms.Form):
    imagen = forms.ImageField(label="Imagen", required=False)

    class Meta:
        model = Avatar
        fields = ['imagen']
        
        
    
        

myweb/tienda/views.py
import email
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import *
from .carro import Carro
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.views.generic import ListView, CreateView
from django.db.models import Q
from .forms import ConctactoForm, ProductoForm, CategoriaForm, UserRegisterForm, UserEditForm, AvatarForm, MensajeForm

    # Create your views here.
    
@login_required
def agregar_avatar(request):
    
    if request.method == "POST":
            
        form = AvatarForm(request.POST, request.FILES)

        if form.is_valid():

            user = User.objects.get(username=request.user.username) # usuario con el que estamos loggueados

            avatar = Avatar(usuario=user, imagen=form.cleaned_data["imagen"])

            avatar.save()

            # avatar = Avatar()
            # avatar.usuario = request.user
            # avatar.imagen = form.cleaned_data["imagen"]
            # avatar.save()

            return redirect("/")

    else:
        form = AvatarForm()
    
    return render(request,"Auth/agregar_avatar.html",{"form":form})
    
    
    

def index(request):
    busqueda = request.POST.get("buscador")
    product_list = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)

    if busqueda:
        product_list = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()
    
    try:
        paginator = Paginator(product_list, 12)
        product_list = paginator.page(page)
    except:
        raise Http404

    data = {'entity': product_list,
            'paginator': paginator
    }
    return render(request, 'index.html', data)


# Listar productos por categoria
def productoxCategoria(request, id):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.filter(categoria = id)
    
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    data = {'entity': lista_productos}
    return render(request, 'index.html', data)


# views productos
def detalleProducto(request, id):
    product = get_object_or_404(Productos, id=id)
    otrosProductos = Productos.objects.filter(categoria=product.categoria)
    data = {
        'producto': product,
        'productosRelacionados': otrosProductos
    }
    return render(request, 'producto/detalle.html', data)


@login_required(login_url='/login')
def addProducto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/listarproductos")
        else:
            data["form"] = formulario   
    return render(request, 'producto/agregar.html', data)


@login_required(login_url='/login')
def listarProductos(request):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()

    try:
        paginator = Paginator(lista_productos, 6)
        lista_productos = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_productos,
            'title': 'LISTADO DE PRODUCTOS',
            'paginator': paginator
            }
    return render(request, 'producto/listar.html', data)


@login_required(login_url='/login')
def editarProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/listarproductos")
        data["form"] = formulario
    return render(request, 'producto/modificar.html', data)


@login_required(login_url='/login')
def deleteProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    producto.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/listarproductos")

def nosotros(request):
    return render(request, 'nosotros.html')

def acerca_de_mi(request):
    return render(request, 'acerca_de_mi.html')

def garantia(request):
    return render(request, 'garantia.html')

def devoluciones(request):
    return render(request, 'devoluciones.html')


# Views categorias
@login_required(login_url='/login')
def listCategorias(request):
    lista_categorias = Categorias.objects.all().order_by('nombre')
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(lista_categorias, 6)
        lista_categorias = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_categorias,
            'title': 'LISTADO DE CATEGORIAS',
            'paginator': paginator
            }

    return render(request,'categorias.html', data)


@login_required(login_url='/login')
def addCategoria(request):
    data = {
        'form': CategoriaForm()
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario
    return render(request, 'categoria/agregar.html', data)


@login_required(login_url='/login')
def modificarCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)

    data = {
        'form': CategoriaForm(instance=categoria)
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST, instance=categoria)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario

    return render(request, 'categoria/modificar.html', data)


@login_required(login_url='/login')
def deleteCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)
    categoria.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/categorias")

def contacto(request):
    data = {
        'form': ConctactoForm()
    }

    if request.method == 'POST':
        formulario = ConctactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Gracias por su mensaje")
        else:
            data["form"] = formulario
    return render(request, 'contacto.html', data)

def mensaje(request):
    data = {
        'form': MensajeForm()
    }

    if request.method == 'POST':
        formulario = MensajeForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Gracias por su mensaje")
        else:
            data["form"] = formulario
    return render(request, 'Auth/mensaje.html', data)

def registrar(request):
    
    if request.method == "POST":
        
        form = UserRegisterForm(request.POST)
       
        if form.is_valid():

            username = form.cleaned_data.get('username')
            firstname = form.cleaned_data.get('firstname')
            lastname = form.cleaned_data.get('lastname')
            email = form.cleaned_data.get('email')
            password1 = form.cleaned_data.get('password1') 
            password2 = form.cleaned_data.get('password2')
            avatar = form.cleaned_data.get('avatar')
            
            form.save() 
            user = authenticate(username=username, password=password1)

            if user is not None:
                login(request, user)
                return render(request,"nosotros.html")

            else:
                return render(request,"Auth/registrar.html")


        return render(request,"Auth/registrar.html",{"form":form})
    
    form = UserRegisterForm()

    return render(request,"Auth/registrar.html",{"form":form})
            
    
                

@login_required
def editar_perfil(request):

    user = request.user 

    if request.method == "POST":
        
        form = UserEditForm(request.POST, instance=user)

        if form.is_valid():

            info = form.cleaned_data
            user.username = info["username"]
            user.first_name = info["first_name"]
            user.last_name = info["last_name"]
            user.email = info["email"]
            

            user.save()

            return render(request,"nosotros.html",{"form":form})
    
    else:
        form = UserEditForm(initial={"email":user.email, "first_name":user.first_name, "last_name":user.last_name,"username":user.username})

    return render(request,"Auth/editar_perfil.html", {"form":form})

    

# Acciones carrito
def viewcart(request):
    return render(request, 'carrito/cart.html', {'carro': request.session['carro']})

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)

myweb/tienda/templates/layouts/tienda.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="tienda ecommerce" />
    <meta name="author" content="Francisco Gomez" />
    <title>Soluciones en Piscinas Uruguay</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %} " />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Bootstrap core JS-->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script> -->


    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-sm navbar-light bg-primary sticky-top">
        <div class="container px-2 px-lg-2">
            <!-- <a class="navbar-brand" href="/">Soluciones en Piscinas Uruguay</a> -->
            <a class="navbar-logo" href="/">
                <!-- <img class="img-fluid" src="{% static 'assets/logo.jpg' %}" width="25%" heigth="25%" alt="logo"> -->
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"></span>
                            Inicio
                        </a>
                    </li>

                    <!-- Menú desplegable -->
                    <div class="dropdown show">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% for categoria in categorias %}
                            <a class="dropdown-item" href="{% url 'tienda:productocategoria' categoria.id %}">{{categoria.nombre}}</a> {% endfor %}
                        </div>
                    </div>

                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/listarproductos">
                                Listado Productos
                            </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/categorias">
                                Listado Categorias
                            </a>
                    </li>

                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/nosotros">
                            Nosotros
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/contacto">
                            Contacto
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/acerca de mi">
                            Acerca de mi
                        </a>
                    </li>
                </ul>

                <ul class="navbar-nav d-flex ml-auto mb-2 mb-lg-0 ms-lg-0">
                    {% if user.is_authenticated %}
                    <!-- Si está autenticado mostrar -->

                    {% load humanize %}
                    <div class="d-flex">
                        <a href="{% url 'tienda:viewcart' %}"   class="btn btn-primary mr-6">
                            <i class="bi-cart-fill sm-5"></i>
                            <span class="badge bg-dark text-white ms-1 rounded-pill">U$S {{ importe_total_carro | intcomma }}</span>
                        </a>
                    </div>
                    
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/editar_perfil">Editar</a>
                        <a class="nav-link active" aria-current="page" href="agregar_avatar">
                            <li class="nav-item"><p class="text-light my-0 mx-0"> {{ user.username }}</p></li>
                            
                    
                            
                                
                            
                            {% if user.avatar.imagen.url %}
                                <img class="rounded" src="{{ user.avatar.imagen.url }}" alt="" srcset="" style="height: 40px;">
                            {% else %}
                                <i class="bi bi-person-circle text-light my-2"></i>
                            
                            
                            
                            {% endif %}
                            
                        
                        </a>
                    </li>
                    
                    <li class="nav-item">
                    
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    
                    
                    
                    {% else %}
                    <!-- Si no está autenticado mostrar -->
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/login">
                            Ingresar
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/registrar">
                            Registrar
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <section class="container">
        <!-- CONTENIDO del LAYOUT -->
        {% block content%} {% endblock %}
    </section>

    <!-- Footer fixed-bottom-->
    <footer class="container-fluid my-0 pt-3 pb-3 bg-dark">
        <!-- <footer class="navbar fixed-bottom navbar-light bg-dark">-->
        <div class="row">
            <ul class="col-4 list-unstyled text-center mx-auto my-auto">
                <h6 class="text-white">Enlaces rápidos</h6>
                

                    <li>
                    <a href="/devoluciones" class="stretched-link text-white">Devoluciones</a></li>

            </ul>
            <ul class="col-4 list-unstyled text-center mx-auto my-auto">
                <img class="img-sm pb-1 " src="{% static 'assets/logo.jpg' %}" alt="logo">
                <p class="font-weight-bold text-white text-center mb-1">Soluciones en Piscinas Uruguay</p>
                <!-- <p class="text-white text-center pb-0 mb-0">Kiyu Man 13 Sol 12, Lomas de Solymar. </p>
                <p class="text-white text-center mb-0">Canelones - Uruguay </p> -->
            </ul>
            <ul class="col-4 list-unstyled my-auto mx-auto text-center">
              {% load bootstrap_icons %}
                <li>
                    <a href="https://www.instagram.com/mantenimiento.piscinas/"> <i class="bi bi-instagram text-white mr-2"></i><span class="badge badge-primary">Instagram</span> </a>
                </li>
            </ul>
        </div>
        <div class="text-center">
            <p class="pt-2 text-white">Copyright &copy; 2021 | All rights Reserved</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- MESSAGES-->
    {% if messages %} {% for message in messages %}
    <script>
        Swal.fire({
            "title": "Felicitaciones!!",
            "text": "{{ message }}",
            "icon": "success"
        })
    </script>
    {% endfor %} {% endif %}
    <!-- END MESSAGES -->
</body>

</html>