myweb/myweb/urls.py
import statistics
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myweb/tienda/urls.py
from logging import root
from xml.dom.minidom import Document
from django.conf import settings
from django.urls import path
from .models import Avatar

from myweb.settings import STATIC_URL
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('acerca de mi/', views.acerca_de_mi, name='acerca_de_mi'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('agregar_avatar', views.agregar_avatar, name='agregar_avatar'),
    path('Auth/mensaje/', views.mensaje, name='mensaje'),
    
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
    
]

myweb/tienda/models.py
from email.mime import image
from io import UnsupportedOperation
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Avatar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='media/avatar', null=True, blank=True)
    
    class meta:
        verbose_name = "avatar"
        verbose_name_plural = "avatares"


class Categorias(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
    class Meta:
        db_table = "categorias"
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


#modelo Productos
class Productos(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imgproductos/%Y/%m/%d', blank=True)
    descripcion = models.CharField(max_length=500)
    precio = models.IntegerField()
    stock = models.IntegerField(null=True, default=0)
    categoria = models.ForeignKey(Categorias, on_delete=models.PROTECT)
    oferta = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre
    class Meta:
        db_table = 'contacto'
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'
        ordering = ['nombre']
        
class Mensaje(models.Model):
    user = models.TextField()
    mensaje = models.TextField()
    fecha = models.DateTimeField()
    
    def __str__(self):
        return self.user
    class Meta:
        db_table = 'mensaje'
        verbose_name = 'Mensaje'
        verbose_name_plural = 'Mensajes'
        ordering = ['fecha']


# Model Carrito

myweb/tienda/forms.py
from django import forms
from .models import Contacto, Mensaje, Productos, Categorias, Avatar
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MensajeForm(forms.ModelForm):
    
    class Meta:
        model = Mensaje
        widgets={
            'mensaje': forms.Textarea(attrs={
                'rows':5,
                'cols':30
                }),
        }
        fields = '__all__'

class ConctactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        widgets={
            'mensaje': forms.Textarea(attrs={
                'rows':5,
                'cols':30
                }),
        }
        fields = '__all__'


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Productos
        fields = ["nombre", "descripcion", "precio", "stock", "categoria", "oferta", "imagen"]
        

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categorias
        fields = ["nombre"]

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)
    first_name = forms.CharField(label="Nombre", required=False)
    last_name = forms.CharField(label="Apellido", required=False)
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput) # la contraseña no se vea
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput)
   
  

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

        #help_texts = {k:"" for k in fields}

class UserEditForm(UserCreationForm):

    username = forms.CharField(label="username")
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput, required=False)
    
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class AvatarForm(forms.Form):
    imagen = forms.ImageField(label="Imagen", required=False)

    class Meta:
        model = Avatar
        fields = ['imagen']
        
        
    
        

myweb/tienda/views.py
import email
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import *
from .carro import Carro
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.views.generic import ListView, CreateView
from django.db.models import Q
from .forms import ConctactoForm, ProductoForm, CategoriaForm, UserRegisterForm, UserEditForm, AvatarForm, MensajeForm

    # Create your views here.
    
@login_required
def agregar_avatar(request):
    
    if request.method == "POST":
            
        form = AvatarForm(request.POST, request.FILES)

        if form.is_valid():

            user = User.objects.get(username=request.user.username) # usuario con el que estamos loggueados

            avatar = Avatar(usuario=user, imagen=form.cleaned_data["imagen"])

            avatar.save()

            # avatar = Avatar()
            # avatar.usuario = request.user
            # avatar.imagen = form.cleaned_data["imagen"]
            # avatar.save()

            return redirect("/")

    else:
        form = AvatarForm()
    
    return render(request,"Auth/agregar_avatar.html",{"form":form})
    
    
    

def index(request):
    busqueda = request.POST.get("buscador")
    product_list = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)

    if busqueda:
        product_list = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()
    
    try:
        paginator = Paginator(product_list, 12)
        product_list = paginator.page(page)
    except:
        raise Http404

    data = {'entity': product_list,
            'paginator': paginator
    }
    return render(request, 'index.html', data)


# Listar productos por categoria
def productoxCategoria(request, id):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.filter(categoria = id)
    
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(descripcion__icontains=busqueda)
        ).distinct()

    data = {'entity': lista_productos}
    return render(request, 'index.html', data)


# views productos
def detalleProducto(request, id):
    product = get_object_or_404(Productos, id=id)
    otrosProductos = Productos.objects.filter(categoria=product.categoria)
    data = {
        'producto': product,
        'productosRelacionados': otrosProductos
    }
    return render(request, 'producto/detalle.html', data)


@login_required(login_url='/login')
def addProducto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/listarproductos")
        else:
            data["form"] = formulario   
    return render(request, 'producto/agregar.html', data)


@login_required(login_url='/login')
def listarProductos(request):
    busqueda = request.POST.get("buscador")
    lista_productos = Productos.objects.order_by('nombre')
    page = request.GET.get('page', 1)
    if busqueda:
        lista_productos = Productos.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()

    try:
        paginator = Paginator(lista_productos, 6)
        lista_productos = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_productos,
            'title': 'LISTADO DE PRODUCTOS',
            'paginator': paginator
            }
    return render(request, 'producto/listar.html', data)


@login_required(login_url='/login')
def editarProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/listarproductos")
        data["form"] = formulario
    return render(request, 'producto/modificar.html', data)


@login_required(login_url='/login')
def deleteProducto(request, id):
    producto = get_object_or_404(Productos, id=id)
    producto.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/listarproductos")

def nosotros(request):
    return render(request, 'nosotros.html')

def acerca_de_mi(request):
    return render(request, 'acerca_de_mi.html')

def garantia(request):
    return render(request, 'garantia.html')

def devoluciones(request):
    return render(request, 'devoluciones.html')


# Views categorias
@login_required(login_url='/login')
def listCategorias(request):
    lista_categorias = Categorias.objects.all().order_by('nombre')
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(lista_categorias, 6)
        lista_categorias = paginator.page(page)
    except:
        raise Http404

    data = {'entity': lista_categorias,
            'title': 'LISTADO DE CATEGORIAS',
            'paginator': paginator
            }

    return render(request,'categorias.html', data)


@login_required(login_url='/login')
def addCategoria(request):
    data = {
        'form': CategoriaForm()
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro agregado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario
    return render(request, 'categoria/agregar.html', data)


@login_required(login_url='/login')
def modificarCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)

    data = {
        'form': CategoriaForm(instance=categoria)
    }
    if request.method == 'POST':
        formulario = CategoriaForm(data=request.POST, instance=categoria)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Registro modificado correctamente")
            return redirect(to="/categorias")
        else:
            data["form"] = formulario

    return render(request, 'categoria/modificar.html', data)


@login_required(login_url='/login')
def deleteCategoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)
    categoria.delete()
    messages.success(request, "Registro eliminado correctamente")
    return redirect(to="/categorias")

def contacto(request):
    data = {
        'form': ConctactoForm()
    }

    if request.method == 'POST':
        formulario = ConctactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Gracias por su mensaje")
        else:
            data["form"] = formulario
    return render(request, 'contacto.html', data)

def mensaje(request):
    data = {
        'form': MensajeForm()
    }

    if request.method == 'POST':
        formulario = MensajeForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Gracias por su mensaje")
        else:
            data["form"] = formulario
    return render(request, 'Auth/mensaje.html', data)

def registrar(request):
    
    if request.method == "POST":
        
        form = UserRegisterForm(request.POST)
       
        if form.is_valid():

            username = form.cleaned_data.get('username')
            firstname = form.cleaned_data.get('firstname')
            lastname = form.cleaned_data.get('lastname')
            email = form.cleaned_data.get('email')
            password1 = form.cleaned_data.get('password1') 
            password2 = form.cleaned_data.get('password2')
            avatar = form.cleaned_data.get('avatar')
            
            form.save() 
            user = authenticate(username=username, password=password1)

            if user is not None:
                login(request, user)
                return render(request,"nosotros.html")

            else:
                return render(request,"Auth/registrar.html")


        return render(request,"Auth/registrar.html",{"form":form})
    
    form = UserRegisterForm()

    return render(request,"Auth/registrar.html",{"form":form})
            
    
                

@login_required
def editar_perfil(request):

    user = request.user 

    if request.method == "POST":
        
        form = UserEditForm(request.POST, instance=user)

        if form.is_valid():

            info = form.cleaned_data
            user.username = info["username"]
            user.first_name = info["first_name"]
            user.last_name = info["last_name"]
            user.email = info["email"]
            

            user.save()

            return render(request,"nosotros.html",{"form":form})
    
    else:
        form = UserEditForm(initial={"email":user.email, "first_name":user.first_name, "last_name":user.last_name,"username":user.username})

    return render(request,"Auth/editar_perfil.html", {"form":form})

    

# Acciones carrito
def viewcart(request):
    return render(request, 'carrito/cart.html', {'carro': request.session['carro']})

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)

myweb/tienda/templates/acerca_de_mi.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-central py-4">Soluciones en Piscinas Uruguay</h3>
        <div class="row py-auto">
            <div class="col-lg-8">
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                Mi nombre es Francisco Gomez De Leon. Estoy muy contento y entusiasmado de seguir estudiando y progresando en CoderHouse.
                Soy de Uruguay vivo en Canelones "ciudad de la costa". El proyecto lo realize solo debido a mi tiempos libres que son entrecortados.
                El proyecto lo enfoque en mi rubro que es a lo que me dedico en la actualidad.
                Trabajo de forma independiente hace 10 años.
                Sufri la perdida de mi padre debido a un accidente de transito hace 9 meses y estudiar es lo que me ha sacado un poco de esta trajica situacion.
                Fui estudiante de java hace 10 años. El volver a estudiar fue un empezar de cero.
                Espero que este proyecto sea de agrado para ustedes.
                Slds. Atte. Francisco Gomez De Leon.

                </p>
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    
                </p>
            </div>

            <div class="col-lg-4 animate__animated animate__bounceInUp animate__delay-0.4s ">
                <img class="img-fluid ml-auto" src="{% static 'assets/Francisco.jpg' %}" alt="Francisco">
            </div>

        </div>
        <div class="row animate__animated animate__bounceInUp animate__delay-1s">
            <p class="mb-1">Teléfono: +598 091890414 | solucionesenpiscinasuruguay@gmail.com</p>
            <p> Canelones, Uruguay</p>
        </div>
    </div>
</div>

{% endblock %}

myweb/tienda/templates/categorias.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">
                            <a href="/addcategoria" class="btn btn-dark btn-sm pull-right" type="submit">
                            Nueva Categoria
                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for categoria in entity %}
                                <tr>
                                    <td>{{ categoria.id }}</td>
                                    <td>{{ categoria.nombre }}</td>
                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:editcategoria' categoria.id %}" type="button"><i class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm" href="{% url 'tienda:deleteCategoria' categoria.id %}" type="button"><i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No se encontraron Productos!!</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myweb/tienda/templates/contacto.html
{% extends 'layouts/tienda.html' %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.2s text-center">CONTACTO</h3>
        <div class="row">
            <div class="col-lg-6 col-sm-04 mx-auto animate__animated animate__bounceInUp animate__delay-0.3s">
                {% load crispy_forms_tags %}
                <form method="post" action="">
                    {% csrf_token %} {{ form | crispy }}
                    <div class="justify-content-center">
                        <button type="reset" class="btn btn-secondary mt-1 mx-2" button ">Cancelar</button>
                        <button type="submit " class="btn btn-danger mt-1 " button ">Enviar</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-sm-04 mt-4 rounded animate__animated animate__backInRight animate__delay-0.4s embed-responsive embed-responsive-4by3">
                <iframe class="embed-responsive-item" <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3275.8336100420643!2d-55.93221058518771!3d-34.81012777595478!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x959f8a24214c53a1%3A0xea4437fda2274f93!2sKiy%C3%BA%201213%2C%2015800%20Ciudad%20de%20la%20Costa%2C%20Departamento%20de%20Canelones!5e0!3m2!1ses-419!2suy!4v1657461966722!5m2!1ses-419!2suy" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>"
                    style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myweb/tienda/templates/devoluciones.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">DEVOLUCIONES</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s ">
                <p class="text-justify">
                    Si el producto entregado al Cliente fuese diferente al solicitado, el mismo Cliente podrá desistir de la compra, y nosotros procederemos a la devolución de valor abonado por este. El Cliente dispone de 5 dias hábiles posterior a la entrega para
                    realizar el reclamo correspondiente. </p>
                <p class="text-justify">El orden de reembolso se realizará dentro de las 48 horas hábiles siguientes al reclamo del Cliente, y se hará efectiva a la cuenta de este según las políticas de las operadoras de tarjetas de crédito.
                </p>
                <p class="text-justify">
                    <span class="font-weight-bold"> Observación:</span> En ningún caso se prodrá proceder a realizar reembolso por un medio diferente al empleado para el pago. En todos los casos se deberá conservar la factura de compra.
                </p>
                <div class="col-10 text-right">
                    <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

myweb/tienda/templates/index.html
{% extends "layouts/tienda.html" %} {% load static %} {% block content %}
<div class="min-vh-100 d-flex flex-colum pb-3">
    <div class="container">

        <!-- Header-->
        <header class="bg-dark py-3 rounded-bottom animate__animated animate__zoomIn animate__delay-0.3s">
            <div class="text-center text-white ">
                <h1 class="display-6 fw-bolder animate__animated animate__bounceInDown animate__delay-0.4s">Soluciones en Piscinas Uruguay</h1>
            
                <h4 class="lead fw-normal mb-0 animate__animated animate__rollIn animate__delay-0.7s">Ofertas hasta 30% off!!!</h4>
            </div>
        </header>

        <!-- Section-->
        <div class="pt-3">
            <form class="d-flex d-md-inlne-block form-inline justify-content-end" method="POST" action="">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-1 small text-center" name="buscador" placeholder="buscar..." value="{{ request.POST.buscador }}">
                    <div class="input-group-append">
                        <button class="btn btn-primary mx-1" type="submit"> 
                    <i class="bi bi-search bi-sm"></i>
                </button>
                    </div>
                </div>
            </form>
        </div>

        <section class="py-2">
            <div class="container px-4 px-lg-5 mt-2 animate__animated animate__fadeIn animate__delay-0.3s">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if entity %} {% for producto in entity %}
                    <div class="col my-3">
                        <div class="card h-100 text-center py-3">
                            <!-- Product image-->
                            {% if producto.imagen %}
                            <img class="mx-auto d-block img-fluid" src="{{ producto.imagen.url }}" alt="producto" width="60px%" /> {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="sinImagen" /> {% endif %}
                            <!-- Product details-->
                            {% load humanize %}
                            <div class="card-body p-3">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                    <!-- Product price-->
                                    U$S {{ producto.precio | intcomma }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-2 pt-2 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-dark mt-auto" href="{% url 'tienda:detalleproducto' producto.id %}">Ver detalle</a> {% if user.is_authenticated%}
                                    <a href="{% url 'tienda:addcart' producto.id %}" class="btn btn-primary mt-2" type="button">
                                        <i class="bi-cart-fill me-1"></i> Agregar al Carrito
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %} {% else %}
                    <div class="text-center text-warning">
                        <h3> No se encontraron Productos!!</h3>
                    </div>
                    {% endif %}
                </div>

                <div>
                    {% include 'paginator.html' %}
                </div>
            </div>

        </section>
    </div>
</div>
{% endblock %}

myweb/tienda/templates/nosotros.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-central py-4">Soluciones en Piscinas Uruguay</h3>
        <div class="row py-auto">
            <div class="col-lg-8">
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                Somos una empresa que se encarga de la instalación y reparacion de piscinas en Uruguay. Contamos con una amplia gama de productos y servicios que pueden ser utilizados por todos los tipos de clientes.
                Nos caracteriza la responsabilidad de ofrecer un servicio de calidad y una atención personalizada.

                </p>
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    
                </p>
            </div>

            <div class="col-lg-4 animate__animated animate__bounceInUp animate__delay-0.4s ">
                <img class="img-fluid ml-auto" src="{% static 'assets/fondo.jpg' %}" alt="team">
            </div>

        </div>
        <div class="row animate__animated animate__bounceInUp animate__delay-1s">
            <p class="mb-1">Teléfono: +598 091890414 | solucionesenpiscinasuruguay@gmail.com</p>
            <p> Canelones, Uruguay</p>
        </div>
    </div>
</div>

{% endblock %}